name = "DynamicPricingExamples"
uuid = "e659ecb8-bdd8-4fa2-bf47-d88ae2a2c926"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
